aws_region           = "us-west-2"
ecr_name             = "dotnet-api"
lambda_role_name     = "apilambdarole"
lambda_function_name = "dotnet-api-lambda"
api_gateway_name     = "inventory-management-api"
account_id           = "847837762102"
